deployments:
  default:
    post_launch:
      - target: code_web_1
        command: exec
        options: {target} bash -c "sleep 30 && python3 manage.py migrate --settings=timestrap.settings.docker"
