version: '3'

services:
  db:
    image: postgres
    environment:
      - PGDATA=/db-data
    volumes:
      - db:/db-data
  redis:
    image: redis
  web:
    build: .
    command: bash ./run_server.sh
    ports:
      - "80:80"
    depends_on:
      - db
      - redis
    environment:
      - SECRET_KEY

volumes:
  db:
